theme: jekyll-theme-cayman

title: Benoit Daigle - Portfolio
# description: "Étudiant | Maîtrise en intelligence artificielle — Université Laval"

# Optionnel : personnalise l'URL sociale affichée en haut de page
# github_username: tonPseudoGitHub
# linkedin_username: tonPseudoLinkedIn

show_downloads: false
